### ISSUE TITLE
Welcome to the Examples repository!

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Examples#1]
I played around a bit with the new Examples repository. All suggestions, criticisms and improvements are welcome.
@KratosMultiphysics/technical-committee, @adityaghantasala, @rubenzorrilla: We should start discussing which categories to create (solids, discrete elements?, thermal flows,...) and propose lists of benchmarks/use cases to include in each.

By the way, you can see the repository [here](https://github.com/KratosMultiphysics/Examples)

**Comment by philbucher** [comment]
@all how do we ensure that these examples are working? The risk is high that they will be outdated.
Do you intend to set it up in a way similar to the tests?

**Comment by jcotela** [comment]
@philbucher you raise a good point, but we don't have an answer. To be honest I'm not sure I'd like to automatize this repository either, in my mind the scripts here should be nice and human-readable, so they can serve as a how-to of sorts for new users.

One thing I was thinking is that maybe we could somehow tag the examples with the Kratos release used to run them, and then update them as needed when a new release comes. I'm sure at least some of them will become outdated with this approach, but then at least we can clearly identify which ones and remove/update them depending on the amount of work required to make them functional again.

**Comment by jcotela** [comment]
For reference: this is the GitHub page of the repository:
https://kratosmultiphysics.github.io/Examples/

**Comment by adityaghantasala** [comment]
@philbucher  I feel it is important that these examples work with the latest release (or some important sub releases). as for the question how do we ensure the examples are working, people who are responsible for the corresponding application should organize this. 

@jcotela  I was thinking that a sub folder for each application (with same name as in the main Kratos repo) and inside this folders sub folders for **Benchmarks** and **TestCases** 

If we make it that the test cases are working with latest release, it is also important to be in sync with GiD problem type (with names and so on).
For the list of TestCases we can see which of the existing "tests". So for example if there is a test for a particular element/feature, may be there is a TestCase/Benchmark (either one) for this.

**Comment by jcotela** [comment]
I just uploaded a first example [page](https://kratosmultiphysics.github.io/Examples/fluid_structure_interaction/validation/fsi_mok/) (just a port from the Mok benchmark in the wiki). I'd like to get some feedback regarding the general layout, missing information which might also be included in the page, and so on: the idea is to prepare some kind of *template* we can use for all future benchmarks.

@adityaghantasala I'm thinking more or less the same as you regarding organization. Just one detail: we have been discussing here about the organization and we are not sure if it is better to go by application or just create broad subject categories: FSI, CFD (both FluidDynamics and trilinos), non-Newtonian flows (implemented within FluidDynamics), Thermal Flows (FluidDynamics+Convection-diffuision applications) and so on. We think potential users might find broad categories more useful than an application-based organization.

**Comment by pooyan-dadvand** [comment]
Nice job @jcotela!
I agree more physics rather than app names because the interested guys would know it better and there are many cases using more than one application
