### ISSUE TITLE
Feast Solver - Eigenfrequencies above ca 6000 Hz

### ISSUE THREAD

**Issue by veiguf** [KratosMultiphysics/Examples#11]
I am a student at the Free University of Bozen-Bolzano, currently working on a study project using Kratos Multiphysics. I am using the FEAST SOLVER to calculate the mode shapes and eigenfrequencies of different components.
It works fine for eigenfrequencies up to ca 6000 Hz, but I am having problems getting results for higher frequencies. I tried  to change the input parameters file "ProjectParameters.json", more precisely I increased the "lambda_max"  up to 2100000000 which seems to be near to the maximum value for which the simulation is running. I understood that the input parameters like "lambda min" and "lambda max" are related to the search interval of the eigenfrequencies, but it is not clear to me for what they exactly stand for.
Any help would be appreciated!

**Comment by jcotela** [comment]
Hi @veiguf. I've moved this issue to the main Kratos repository to give it more visibility (not all Kratos developers follow the Examples repository).
