### ISSUE TITLE
eigenvalue and eigenvector in python

### ISSUE THREAD

**Issue by MagaFem** [KratosMultiphysics/Examples#12]
possible to get the eigenvalue- and eigenvector-results to python-workspace?

Examples/structural_mechanics/validation/beam_eigenvalue_analysis/source/MainKratos.py

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/structural-mechanics I think this question is for you.

**Comment by philbucher** [comment]
Hi @MagaFem ,
simply do the following at the end of the script:
~~~py
print(main_model_part.ProcessInfo[EIGENVALUE_VECTOR])
print(main_model_part.GetNode(1).GetValue(EIGENVECTOR_MATRIX)) # for node with id 1
# to get the output on every node:
for node in main_model_part.Nodes:
    print(node.GetValue(EIGENVECTOR_MATRIX))
~~~

**Comment by philbucher** [comment]
@MagaFem I updated the script, this should get you started ;)
Just reopen this issue if you have more questions
