### ISSUE TITLE
Mmg remeshing - Contact structural mechanics examples

### ISSUE THREAD

**Issue by Marco1410** [KratosMultiphysics/Examples#125]
Hi! I'm trying to update the contact examples that are in the Mmg folder but they aren't working correctly.

I've changed a few things locally but can't get them to work. I think it may be an application problem.

@rubenzorrilla It would be helpful if someone could take a look at them.

The examples are:

-  contact_hessian
-  contact_spr
-  contacting_cylinders 
-  hertz_hessian

**Comment by loumalouomega** [comment]
Remeshing can not work because it depends of a PR that was never merged

**Comment by rubenzorrilla** [comment]
Same comment. If so I think we should remove them.

**Comment by loumalouomega** [comment]
Same as other issue, I wil do it

**Comment by Marco1410** [comment]
Thanks a lot @loumalouomega , so I close both issues.

**Comment by rubenzorrilla** [comment]
Lets leave it open as a reminder for @loumalouomega.

**Comment by loumalouomega** [comment]
Done, backup in this branch: https://github.com/KratosMultiphysics/Examples/tree/restore-mmg-tests
