### ISSUE TITLE
Mmg remeshing - Structural mechanics examples

### ISSUE THREAD

**Issue by Marco1410** [KratosMultiphysics/Examples#126]
Hi! I think the beams Mmg remeshing examples don't work well. Possibly it's something in the app that hasn't been updated.

@rubenzorrilla, Who could look at them to try to make them work?

The examples are:

- beam_spr
- beam2D
- beam2D_internal_interpolation

**Comment by loumalouomega** [comment]
Remeshing can not work because it depends of a PR that was never merged

**Comment by rubenzorrilla** [comment]
If so I think we should temporary remove those.

**Comment by loumalouomega** [comment]
> If so I think we should temporary remove those.

I will do it, I will do a separated branch to restore at some point

**Comment by rubenzorrilla** [comment]
Lets leave it open as a reminder for @loumalouomega.

**Comment by loumalouomega** [comment]
Done, backup in this branch: https://github.com/KratosMultiphysics/Examples/tree/restore-mmg-tests
