### ISSUE TITLE
[Fluid] Kelvin-Helmholtz instability

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Examples#38]
I tried to run the case using the source files provided and it gave me a nan in the first iteration.

**Comment by adityaghantasala** [comment]
Hi Ruben  
 I expected this ! 
Have a look at the discussion here 

https://github.com/KratosMultiphysics/Kratos/issues/4121

to make this case working , we need to change 

https://github.com/KratosMultiphysics/Kratos/blob/b099526953b2d7156528ed53c61dbf4d9a22163e/applications/FluidDynamicsApplication/python_scripts/navier_stokes_solver_vmsmonolithic.py#L335

we should discuss it with Jordi to see if it makes sense to change this now or later (this means it will remain a non working example)

**Comment by rubenzorrilla** [comment]
OK @adityaghantasala I'll keep the issue opened as a reminder. Thanks!
