### ISSUE TITLE
Permission to push a branch

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Examples#46]
Hi, I'm trying to push a branch to migrate examples from KratosMultiphysics to Examples repo, but I'm getting a permission error:
~~~sh
mmaso@PCCB019:~/Examples$ git push --set-upstream origin pfem2-migrating-examples 
Username for 'https://github.com': mmaso@cimne.upc.edu
Password for 'https://mmaso@cimne.upc.edu@github.com': 
remote: Permission to KratosMultiphysics/Examples.git denied to miguelmaso.
fatal: unable to access 'https://github.com/KratosMultiphysics/Examples.git/': The requested URL returned error: 403
~~~
@philbucher do you know how to get access to that repo?

**Comment by philbucher** [comment]
I added the shallow-water team, can you please try again?

@roigcarlo can we automatically add all teams from the Kratos-Repo also to the Examples-repo?

**Comment by roigcarlo** [comment]
mm sadly no

**Comment by miguelmaso** [comment]
thanks
