### ISSUE TITLE
Shape optimization example is not following the structure of thie repo

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Examples#67]
https://github.com/KratosMultiphysics/Examples/tree/master/shape_optimization

It will be nice if this examples followed the structure of the others, with the corresponding description and previews of the examples. Just that

**Comment by armingeiser** [comment]
I agree, however i am afraid i don't have time to solve this at the moment. I keep it on my TODO

**Comment by armingeiser** [comment]
@dbaumgaertner ?

**Comment by dbaumgaertner** [comment]
I also agree. Also, there should be some description of the test cases. However, I am not sure, whether I get to do it the next time. So for the moment, I am afraid it has to stay like this.

**Comment by loumalouomega** [comment]
I will add the label TODO

**Comment by loumalouomega** [comment]
Ping @armingeiser and @dbaumgaertner . I will close this
